title: Home
views:
  - title: Main
    path: main
    icon: mdi:home-assistant
    badges:
      - entity: sensor.livingroom_sensor_temperature
      - entity: sensor.livingroom_sensor_humidity
      - entity: sensor.livingroom_sensor_pressure
      - entity: sensor.movement_sensor_illuminance
      - entity: binary_sensor.movement_sensor_occupancy
    cards:
      - type: entities
        entities:
          - entity: light.livingroom_light_left
          - entity: light.livingroom_light_right
          - entity: light.led_light
          - entity: cover.livingroom_cover_position
  - title: Service
    path: service
    icon: mdi:view-module-outline
    cards:
      - type: entities
        entities:
          - switch.zigbee_permit_join
          - type: divider
          - sensor.button1_battery
          - sensor.button2_battery
          - sensor.movement_sensor_battery
          - sensor.livingroom_sensor_battery
